from .property_names import *

md17_property_keys = {energy: 'E',
                      force: 'F',
                      delta_energy_1: 'Delta_E1',
                      delta_energy_2: 'Delta_E2',
                      delta_force_1: 'Delta_F1',
                      delta_force_2: 'Delta_F2',
                      atomic_position: 'R',
                      atomic_type: 'z',
                      idx_i: 'idx_i',
                      idx_j: 'idx_j',
                      pair_mask: 'pair_mask',
                      bond_prob: 'bond_prob',
                      bond_mask: 'bond_mask',
                      bond_prob_s0: 'bond_prob_s0',
                      bond_mask_s0: 'bond_mask_s0',
                      bond_prob_s1: 'bond_prob_s1',
                      bond_mask_s1: 'bond_mask_s1',
                      bond_prob_s2: 'bond_prob_s2',
                      bond_mask_s2: 'bond_mask_s2',
                      unit_cell: 'unit_cell',
                      pbc: 'pbc',
                      cell_offset: 'cell_offset',
                      stress: 'stress',
                      node_mask: 'node_mask'}

qm7x_property_keys = {energy: 'ePBE0+MBD',
                      force: 'totFOR',
                      delta_energy_1: 'Delta_E1',
                      delta_energy_2: 'Delta_E2',
                      delta_force_1: 'Delta_F1',
                      delta_force_2: 'Delta_F2',
                      atomic_position: 'atXYZ',
                      atomic_type: 'atNUM',
                      hirshfeld_volume: 'hVOL',
                      hirshfeld_volume_ratio: 'hRAT',
                      partial_charge: 'hCHG',
                      total_dipole_moment: 'vDIP',
                      idx_i: 'idx_i',
                      idx_j: 'idx_j',
                      pair_mask: 'pair_mask',
                      bond_prob: 'bond_prob',
                      bond_mask: 'bond_mask',
                      bond_prob_s0: 'bond_prob_s0',
                      bond_mask_s0: 'bond_mask_s0',
                      bond_prob_s1: 'bond_prob_s1',
                      bond_mask_s1: 'bond_mask_s1',
                      bond_prob_s2: 'bond_prob_s2',
                      bond_mask_s2: 'bond_mask_s2',
                      node_mask: 'node_mask'
                      }

# Delta-offset-only mappings are merged explicitly by its trainer. Keeping them
# separate preserves legacy ground/standard-delta prop_keys and scales metadata.
delta_offset_property_keys = {
    offset_energy: 'Offset_E',
    offset_force: 'Offset_F',
    pred_energy_0: 'pred_E0',
    pred_force_0: 'pred_F0',
    active_state: 'astate',
}
